#!/bin/sh

# requires pandoc and a TeX installation with the Baskervald font
LATEX_TEMPLATE=styles/resume2
OUTFILE=$(basename $1 .md)
pandoc --pdf-engine=lualatex --template $LATEX_TEMPLATE --metadata fontsize=9pt --metadata title="Engineer. Applied Philosopher. Code Janitor. Symmathecist" -V geometry:"left=.75in, right=.5in" -V linestretch=.8 -V mainfont="baskerville" ${1} -f gfm -o ${OUTFILE}.pdf
